import { prisma } from '@/lib/prisma';
import { auth } from '@/auth';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { formatINR } from '@/lib/utils/conversions';
import { AdminQuotationDialog } from './quotation-dialog';

export default async function AdminQuotations() {
  const session = await auth();
  if (!session || session.user?.role !== 'ADMIN') return null;

  const quotations = await prisma.quotation.findMany({
    orderBy: { createdAt: 'desc' },
    include: { items: { include: { product: true } }, user: true },
  });

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Global Quotations</h1>
        <p className="text-muted-foreground">View all quotations generated by sellers across the platform.</p>
      </div>

      <div className="rounded-md border bg-card">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Quotation #</TableHead>
              <TableHead>Date</TableHead>
              <TableHead>Seller</TableHead>
              <TableHead>Item</TableHead>
              <TableHead>Quantity</TableHead>
              <TableHead>Total Amount</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {quotations.map((quo) => {
              const item = quo.items[0];
              return (
                <TableRow key={quo.id}>
                  <TableCell className="font-medium">{quo.quotationNumber}</TableCell>
                  <TableCell>{quo.createdAt.toLocaleDateString()}</TableCell>
                  <TableCell>{quo.user.name} <br/><span className="text-xs text-muted-foreground">{quo.user.email}</span></TableCell>
                  <TableCell>{item.product.name}</TableCell>
                  <TableCell>{item.requestedQuantity.toString()} {item.requestedUnit}</TableCell>
                  <TableCell>{formatINR(quo.totalAmount)}</TableCell>
                  <TableCell>
                    <Badge variant={quo.status === 'GENERATED' ? 'default' : 'secondary'}>
                      {quo.status}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <AdminQuotationDialog quotation={quo} />
                  </TableCell>
                </TableRow>
              );
            })}
            {quotations.length === 0 && (
              <TableRow>
                <TableCell colSpan={8} className="text-center py-8 text-muted-foreground">
                  No quotations found.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
